[tool.poetry]
name = "webexmemebot"
version = "0.1.0"
description = "Webex-based meme generation bot using memegen.link."
authors = ["luketainton"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11.2"
webex-bot = "^0.5.1"
pillow = "^10.3.0"
sentry-sdk = "^2.2.0"

[tool.poetry.group.dev.dependencies]
black = "^24.4.2"
coverage = "^7.5.1"
pylint = "^3.2.0"
pylint-exit = "^1.2.0"
pytest = "^8.2.0"
pre-commit = "^3.7.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
meme = "app.main:main"
