[tool.poetry]
name = "webexmemebot"
version = "0.1.0"
description = "Webex-based meme generation bot using memegen.link."
authors = ["luketainton"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11.2"
webex-bot = "^0.4.7"
pillow = "^10.3.0"
sentry-sdk = "^1.45.0"

[tool.poetry.group.dev.dependencies]
black = "^24.4.0"
coverage = "^7.4.4"
pylint = "^3.1.0"
pylint-exit = "^1.2.0"
pytest = "^8.1.1"
pre-commit = "^3.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
meme = "app.main:main"
