name: Build
on:
  push:
    branches: [main]

jobs:
  build:
    name: GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GHCR_ACCESS_TOKEN }} | docker login ghcr.io -u luketainton --password-stdin
      - name: Build image for GitHub Package Registry
        run: docker build . --file Dockerfile --tag ghcr.io/luketainton/webexmemebot:${{ github.sha }} --tag ghcr.io/luketainton/webexmemebot:latest
      - name: Push image to GitHub Package Registry
        run: |
          docker push ghcr.io/luketainton/webexmemebot:latest
          docker push ghcr.io/luketainton/webexmemebot:${{ github.sha }}
